### PR TITLE
Migrated site to Material for MkDocs

### PR DESCRIPTION
**Pull request by tomvanenckevort-hp**
- Migrated the existing Reuse Standard to use [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/). This provides a number of advantages:
  - Better and consistent site navigation.
  - Automatic display of the standard versions (based on Git branches), so people can view different versions of the standard.
  - Flow diagrams are now generated in code using [Mermaid](https://mermaid.js.org/), which means it's easier to update them without having to edit images.
- Added new GitHub Actions workflow that will build and deploy the site to GitHub Pages whenever it gets merged to the `main` branch. NOTE: currently GH Pages is set up to use the `main` branch for the site, but this will need to be changed to use the `gh-pages` branch instead (that's where the build action will push the built files).

All the content from the current standard has been copies across as-is, so no changes required to the version numbers.

### CODE REVIEW

**Review by kim-reath — APPROVED** [review]
@tomvanenckevort-hp lgtm! Do you need me to update the branches for the Pages deployment?

**Comment by tomvanenckevort-hp** [comment]
@kim-reath Yes please!

**Comment by kim-reath** [comment]
@tomvanenckevort-hp cool I've just updated that to be `gh-pages` now:
image

**Comment by tomvanenckevort-hp** [comment]
@kim-reath I've just merged the PR and the build completed fine (all correct files are in the `gh-pages` branch). But the site now shows a 404.

Can you just double-check the settings are still as per your screenshot after the build was done?

**Comment by kim-reath** [comment]
@tomvanenckevort-hp it looked like the custom domain value had disappeared. I've added that back in and doesn't seem to be a 404 for me now.

**Comment by tomvanenckevort-hp** [comment]
@kim-reath All good now. Thanks!

**Pull request merged**
